### ISSUE TITLE
SQLite for Universal Windows Platform not loading

### ISSUE THREAD

**Issue by PeterWallenius** [Microsoft-Build-2016/CodeLabs-UWP#3]
I'm running Windows 10 (14295) and VS2015 Update 2.

When I open the project (Microsoft.Labs.SightsToSee - module1,begin) it cannot restore the nuget package **SQLite for Universal Windows Platform **(SQLite.UWP.2015: v3.11.1).

How do I restore this, what is the name of the noget package?

**Comment by PeterWallenius** [comment]
Found the solution

Its a Universal Windows Extension, and the current version is 3.12.0

**Comment by michaeldvz** [comment]
I had the same issue when I downloaded the project yesterday.  Noted that AndyCW uploaded SDK DLLs.  The issue with SQLite.UWP.2015: v3.11.1 has been resolved and updated to 3.12.0.  Now builds and runs correctly.  The new files resolved the issue for me.  Thanks.

**Comment by AndyCW** [comment]
The project no longer depends on separate downloading of the SQLite Visual Studio Extension SDK as I have included the necessary SDK files in the repo.
