### ISSUE TITLE
System.IO.FileNotFound Exception + VoiceCommands.xml

### ISSUE THREAD

**Issue by niko-achilles** [Microsoft-Build-2016/CodeLabs-UWP#4]
I get the exception relative to the file voice command. Name of the File VoiceCommands.xml

the line of code throws a System.IO.FileNotFound Exception.

`await Windows.ApplicationModel.VoiceCommands.VoiceCommandDefinitionManager.InstallCommandDefinitionsFromStorageFileAsync(storageFile);`

In order to produce a working software changed the followingin project settings:
VoiceCommands.xml - > Properties -> Copy if newer

In the installation path of the Softare bin/../AppX I can see the file together with the .exe file of the application (Microsoft.Labs.SightsToSee.exe)

The Application still throws an System.IO.FileNotFound Exception.

**Comment by AndyCW** [comment]
This FileNotFound exception is misleading. It is actually due to a bug in the WinRT voice command APIs when it cannot successfully parse the contents of the VoiceCommands.xml vcd file.
I have reproduced this bug on a system running OS build 14328, but it works fine on another machine running OS build 14295 - both systems have the 14295 SDK installed.

What is your machine configuration?

**Comment by niko-kokkinos** [comment]
Tried to run the application on systems with the following OS Build 
maschine 1. 14316 -> failded (FileNotFound exception )
maschine 2. 14295 -> failded (FileNotFound exception )

maschine 2 is the same as maschine 1 , but i have uninstalled OS Build runtime 14316 via windows updates -> unistall and then installed the OS Runtime 14295 via the Slow Ring update configuration.

**Comment by AndyCW** [comment]
Curious. Your machine 2 sounds the same. Can we check details?:
I have Windows 10 Enterprise Insider Preview Build 14295.rs1_release.160318-1628
SDK: 10.0.14295.1000
Visual Studio 2015 Update 2 with Tools for Windows 1.3.1

The handling of these vcd files does seem temperamental in recent builds. During development of these labs we encountered this problem with an earlier build, but the problems went away with 14292 (the build we used in the labs at BUILD). There are a number of changes going on with voice commands in the current development cycle, so some issues may well persist with Insider Builds for a little while yet.

**Comment by niko-kokkinos** [comment]
@AndyCW 
you are right . maschine 2 sounds the same , but is not the same . I installed the OS Build Runtime again, but the installed 14295 sdk was that , that left from the previous Build installation. 

So, i uninstalled the 14295 sdk and installed the 14295 sdk again. It works.
